def graphic_welcome
    puts "-------------------------------------------------------------------------------------------------------------"
    puts "|                    __        __     _                                   _                                 |"
    puts "|                    \\ \\      / /___ | |  ___  ___   _ __ ___    ___     | |_  ___                          |"
    puts "|                     \\ \\ /\\ / // _ \\| | / __|/ _ \\ | '_ ` _ \\  / _ \\    | __|/ _ \\                         |"
    puts "|                      \\ V  V /|  __/| || (__| (_) || | | | | ||  __/    | |_| (_) |                        |"
    puts "|                       \\_/\\_/  \\___||_| \\___|\\___/ |_| |_| |_| \\___|     \\__|\\___/                         |"
    puts "|                                                                                                           |"
    puts "|                                                                                                           |"
end

def graphic_thanks
    puts "-------------------------------------------------------------------------------------------------------------"
    puts "|       _____  _                    _               __                               _                      |"
    puts "|      |_   _|| |__    __ _  _ __  | | __ ___      / _|  ___   _ __      _   _  ___ (_) _ __    __ _        |"
    puts "|        | |  | '_ \\  / _` || '_ \\ | |/ // __|    | |_  / _ \\ | '__|    | | | |/ __|| || '_ \\  / _` |       |"
    puts "|        | |  | | | || (_| || | | ||   < \\__ \\    |  _|| (_) || |       | |_| |\\__ \\| || | | || (_| |       |"
    puts "|        |_|  |_| |_| \\__,_||_| |_||_|\\_\\|___/    |_|   \\___/ |_|        \\__,_||___/|_||_| |_| \\__, |       |"
    puts "|                                                                                              |___/        |"
    puts "|                                                                                                           |"
end

def graphic_bottom
    puts "|           ________                           __________               .__                                 |"
    puts "|          /  _____/ _____     _____    ____   \\______   \\  ____ ___  __|__|  ____ __  _  __ ______         |"
    puts "|         /   \\  ___ \\__  \\   /     \\ _/ __ \\   |       _/_/ __ \\\\  \\/ /|  |_/ __ \\\\ \\/ \\/ //  ___/         |"
    puts "|         \\    \\_\\  \\ / __ \\_|  Y Y  \\\\  ___/   |    |   \\\\  ___/ \\   / |  |\\  ___/ \\     / \\___ \\          |"
    puts "|          \\______  /(____  /|__|_|  / \\___  >  |____|_  / \\___  > \\_/  |__| \\___  > \\/\\_/ /____  >         |"
    puts "|                 \\/      \\/       \\/      \\/          \\/      \\/                \\/             \\/          |"
    puts "|                                                                                                           |"
    puts "|                         .:+oyhhddddddddddddddddddddddddddddddddddddddddddddhyso/-`                        |"
    puts "|                     .+ymMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmy/.                    |"
    puts "|                  .odMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd+`                 |"
    puts "|                .yMMMMMMMMNhs+/:-------------------------------------------::/+sdNMMMMMMMNo`               |"
    puts "|              `oMMMMMMMd+.                                                       `-omMMMMMMN+`             |"
    puts "|             .dMMMMMMy-                                                              -hMMMMMMh`            |"
    puts "|            -NMMMMMd-         :+ooo+`                                   ./++-          :mMMMMMm.           |"
    puts "|           .mMMMMMs`         .MMMMMMs                                  /MMMMMs          `hMMMMMd`          |"
    puts "|           yMMMMMy           .MMMMMMs                                  yMMMMMm           `dMMMMMo          |"
    puts "|          .MMMMMN`      .....:MMMMMMy.....`                       `..  `odmms.  `.`       -MMMMMN`         |"
    puts "|          +MMMMMy      yMMMMMMMMMMMMMMMMMMN.                    `sNMMNo`      /mMMMh.      dMMMMM-         |"
    puts "|          oMMMMMo      mMMMMMMMMMMMMMMMMMMM:                    /MMMMMM-     `NMMMMMy      yMMMMM:         |"
    puts "|          +MMMMMs      hMMMMMMMMMMMMMMMMMMM-                    `hMMMMs`      +NMMMd-      dMMMMM-         |"
    puts "|          .MMMMMN`     `-----/MMMMMMy-----.                       `--` `+hdho` `--.       .MMMMMN`         |"
    puts "|           hMMMMMs           .MMMMMMs                                  sMMMMMd           `hMMMMMo          |"
    puts "|           .NMMMMMo          .MMMMMMs                                  +MMMMMy          `yMMMMMm`          |"
    puts "|            :NMMMMMy.         /sssso.        `/++++++++++++++:          -oso:          .dMMMMMm.           |"
    puts "|             -mMMMMMNo`                    `:dMMMMMMMMMMMMMMMMh-                     .sMMMMMMd.            |"
    puts "|              `yMMMMMMMy/`              `-omMMMMMMMMMMMMMMMMMMMMdo-               .+hMMMMMMMo`             |"
    puts "|                -hMMMMMMMMdy+/-....-:+shNMMMMMMMmsoooooooosNMMMMMMMNho/:-...-:/oymMMMMMMMMy.               |"
    puts "|                  -sNMMMMMMMMMMMMMMMMMMMMMMMMMh/`          `+dMMMMMMMMMMMMMMMMMMMMMMMMMmo.                 |"
    puts "|                    `:odMMMMMMMMMMMMMMMMMMmy/`                .+yNMMMMMMMMMMMMMMMMMNho-                    |"
    puts "|                        `-/oyhhhhhhhhys+:`                        .:+syhhhhhhhhso/-`                       |"
    puts "|                                                                                                           |"
    puts "-------------------------------------------------------------------------------------------------------------"
end