  



  # Artist.create(name: "Dirty Rugs" , genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "dirty_rugs")
  # Artist.create(name: "Sundog" , genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "sundog")
  # Artist.create(name: "The Dip" , genre: "Soul", password: "p@ssword", password_hint: "p@ssword", username: "the_dip")
  # Artist.create(name: "General Mojo's", genre: "Indie", password: "p@ssword", password_hint: "p@ssword", username: "general_mojos")
  # Artist.create(name: "Lanford Black", genre: "Soul", password: "p@ssword", password_hint: "p@ssword", username: "lanford_black")
  # Artist.create(name: "Po' Brothers" , genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "po_brothers")
  # Artist.create(name: "Beverly Crusher", genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "beveryly_crusher")
  # Artist.create(name: "Kinski", genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "kinski")
  # Artist.create(name: "Head Band", genre: "Rock", password: "p@ssword", password_hint: "p@ssword", username: "head_band")
  # Artist.create(name: "Cumulus" , genre:"Indie", password: "p@ssword", password_hint: "p@ssword", username: "cumulus")
  # Artist.create(name: "Antonioni", genre: "Indie", password: "p@ssword", password_hint: "p@ssword", username: "antonioni")
  # Artist.create(name: "Duke Evers" , genre:"Rock", password: "p@ssword", password_hint: "p@ssword", username: "duke_evers")


  # Venue.create(name: "Sunset Tavern", street_address: "5433 Ballard Ave NW", city: "Seattle", zip_code: 98107, capacity: 200, password: "p@ssword", password_hint: "p@ssword", username: "sunset_tavern")
  # Venue.create(name: "Conor Byrne", street_address: "5140 Ballard Ave NW", city: "Seattle" , zip_code: 98107, capacity: 125, password: "p@ssword", password_hint: "p@ssword", username: "conor_byrne")
  # Venue.create(name: "Central Saloon", street_address: "207 1st Ave S", city: "Seattle", zip_code: 98104, capacity: 150, password: "p@ssword", password_hint: "p@ssword", username: "central_saloon")
  # Venue.create(name: "Neumos", street_address: "925 E Pike St", city: "Seattle", zip_code: 98122, capacity: 675, password: "p@ssword", password_hint: "p@ssword", username: "neumos")
  # Venue.create(name: "Barboza", street_address: "925 E Pike St", city: "Seattle", zip_code: 98122, capacity: 200, password: "p@ssword", password_hint: "p@ssword", username: "barboza")
  # Venue.create(name: "Chop Suey", street_address: "1325 E Madison St", city: "Seattle", zip_code: 98122, capacity: 450, password: "p@ssword", password_hint: "p@ssword", username: "chopsuey")
  # Venue.create(name: "Tim's Tavern", street_address: "602 N 105th St", city: "Seattle", zip_code: 98133, capacity: 75, password: "p@ssword", password_hint: "p@ssword", username: "tims_tavern")
  # Venue.create(name: "Clock Out Lounge", street_address: "4864 Beacon Ave S", city: "Seattle", zip_code: 98108, capacity: 99, password: "p@ssword", password_hint: "p@ssword", username: "clockout")
  # Venue.create(name: "Belltown Yacht Club", street_address: "2320 1st Ave", city: "Seattle", zip_code: 98121, capacity: 110, password: "p@ssword", password_hint: "p@ssword", username: "belltown_yacht_club")

  # Event.create(date: "2020-1-11" ,artist_id: 1, venue_id: 4)
  # Event.create(date: "2019-5-12" ,artist_id: 1, venue_id: 5)
  # Event.create(date: "2020-4-17" ,artist_id: 2, venue_id: 7)
  # Event.create(date: "2020-1-11" ,artist_id: 2, venue_id: 2)
  # Event.create(date: "2020-12-11" ,artist_id: 3, venue_id: 1)
  # Event.create(date: "2020-1-11" ,artist_id: 3, venue_id: 6)
  # Event.create(date: "2020-1-11" ,artist_id: 4, venue_id: 3)
  # Event.create(date: "2020-11-11" ,artist_id: 4, venue_id: 8)
  # Event.create(date: "2020-1-11" ,artist_id: 5, venue_id: 5)
  # Event.create(date: "2020-10-11" ,artist_id: 5, venue_id: 4)
  # Event.create(date: "2020-3-11" ,artist_id: 6, venue_id: 3)
  # Event.create(date: "2020-1-11" ,artist_id: 6, venue_id: 9)
  # Event.create(date: "2020-06-11" ,artist_id: 7, venue_id: 1)
  # Event.create(date: "2020-1-11" ,artist_id: 7, venue_id: 5)
  # Event.create(date: "2020-1-11" ,artist_id: 7, venue_id: 6)
  # Event.create(date: "2020-9-11" ,artist_id: 8, venue_id: 8)
  # Event.create(date: "2020-1-11" ,artist_id: 9, venue_id: 3)
  # Event.create(date: "2020-1-11" ,artist_id: 3, venue_id: 3)
  # Event.create(date: "2020-1-11" ,artist_id: 12, venue_id: 8)
  # Event.create(date: "2020-1-11" ,artist_id: 10, venue_id: 2)
  # Event.create(date: "2020-1-11" ,artist_id: 11, venue_id: 2)
